### ISSUE TITLE
Error:   Please commit your changes or stash them before you switch branches.

### ISSUE THREAD

**Issue by nachg** [stefanzweifel/git-auto-commit-action#158]
If there are some changes in a previously added file, such error will be thrown:
```
  > Switching/creating branch...
  Error: Error: error: Your local changes to the following files would be overwritten by checkout:
  	.github/badges/jacoco.svg
  Please commit your changes or stash them before you switch branches.
  Aborting
```

Steps to reproduce:
1) Add a step to the job that will generate some file with dynamic content
2) Add add-and-commit@ action after the previous step
3) Run Job more than one time

Actual result: message from above
Expected results: changed files should be committed.

Logs:
[logs_54.zip](https://github.com/stefanzweifel/git-auto-commit-action/files/6436946/logs_54.zip)

**Comment by stefanzweifel** [comment]
This sound similar to this previous issue: https://github.com/stefanzweifel/git-auto-commit-action/issues/155

`git-auto-commit` will not resolve such complex git issues for you. 
If this is something that regularly can happen in your workflows, make sure to write your workflow so that such issues resolve themselves.

From your comment and the zipped log I assume that you have a lengthy workflow which does some stuff and **at the end** you switch branches and want to to commit those files.

Maybe you can try switching to a new branch earlier or stashing and unstashing the files on your own?

**Comment by nachg** [comment]
I agree. Sorry for Disturbing you. This is not a problem of this project.

**Comment by stefanzweifel** [comment]
No problem! Always happy to help or clarify things.
