### ISSUE TITLE
Cannot use this action in Reusable Workflow

### ISSUE THREAD

**Issue by edmondo1984** [stefanzweifel/git-auto-commit-action#216]
This action is relying on some context / environment variable from the GitHub pipeline, so it is not suitable to be run in a pipeline which workflow triggers is `workflow_call`

fatal: could not read Username for 'https://github.com/': No such device or address

**Comment by edmondo1984** [comment]
You are right, it was the v2 thing. My fault :( 

Now it works! Although, the commit invalidate all the checks on the PR :(

**Comment by stefanzweifel** [comment]
> Although, the commit invalidate all the checks on the PR :(

Yeah, that a limitation by GitHub. Instead of using the default `GITHUB_TOKEN` you could issue your own personal acces token and use that token to make the commit. More information on this here: https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs

Commits made by `git-auto-commit` would then retrigger all your checks again. Just beware that you don't create an infinite recursion ;)
