### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by SevereCloud** [stefanzweifel/git-auto-commit-action#250]
### git-auto-commit Version

v4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L14

https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L27

https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L104

### Steps to reproduce

Run and see annotations

### Example Workflow

```yaml
-
```

**Comment by stefanzweifel** [comment]
Thanks for letting me know!
Another user reported this through this discussion already: https://github.com/stefanzweifel/git-auto-commit-action/discussions/248

Will push a fix in the coming days.

**Comment by stefanzweifel** [comment]
Reopening this as the Action now fails for GitHub enterprise users with an outdated runner (#254).
Will …

- re-add the old syntax so both approches are supported
- remove the old syntax again towards the end of the year, as most enterprise users will hopefully have updated their runners by then.
- add a big warning to the README / issues forms, that the warning users are seing in their logs regarding "set-output" are already fixed in the Action

**Comment by stefanzweifel** [comment]
The Action has been updated to use the old syntax, if the underlying Actions runner has not yet been updated. (See #255).

A new version `v4.15.3` has been tagged. (See discussion here: https://github.com/stefanzweifel/git-auto-commit-action/discussions/256)
The alias for `v4` has been updated to point from `v4.15.1` to `v4.15.3`.
