### ISSUE TITLE
BUG: Default Commit username and email

### ISSUE THREAD

**Issue by actuarysailor** [stefanzweifel/git-auto-commit-action#331]
### git-auto-commit Version

V5.0.1

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

The default username and email you use does not have permission to repo.  You documentation does not show how to grant permissions either since it is not a valid GitHub user account.

### Steps to reproduce

▶ Run stefanzweifel/git-auto-commit-action@v5.0.1
![image](https://github.com/stefanzweifel/git-auto-commit-action/assets/24359398/d8c3ed60-ef43-4662-b88e-ba057a2496bb)

### Tried solutions

Tried granting your GitHub bot permission, but GitHub says unable to find user to add as collaborator

### Example Workflow

```yaml
https://github.com/actuarysailor/gha-repo-manager/actions/runs/9341254332/job/25707872777#step:5:1
```

### Relevant log output

```shell
See above
```

**Comment by actuarysailor** [comment]
Nevermind, if you provide a token to the action/checkout step it works...  Not sure I saw reference to this in your documentation, might prevent future users from raising bad issues...

**Comment by stefanzweifel** [comment]
Thanks for opening an issue.

> The default username and email you use does not have permission to repo.

The default username or email for the commit has nothing do to with the permissions, if a commit can be pushed. These default values just represent the "Github Actions" user and help differentiate commits made from bots and users.

The first few lines of the usage documentation explain, that the `contents`-permission has to be set on the job level, so that the default GITHUB_TOKEN applied by GitHub Actions has access to push a commit back to the repository.[^1]

A custom access token is required if your repository has certain settings enabled (like protected branches). As the majority of repos doesn't use the settings, the documentation for this is a bit further down in the README.

---

As your link to the example workflows leads to a 404 page, I can't give you more details on why your experience with the action wasn't up to par.

[^1] I agree, that the inner-workings of how the GITHUB_TOKEN is used, is too hidden. I will try to incorporate this into the documentation.
