### ISSUE TITLE
"All checks have passed" disappears

### ISSUE THREAD

**Issue by dellow** [stefanzweifel/git-auto-commit-action#37]
**Version of the Action**
`v2.5.0`

**Describe the bug**
This isn't really a bug, but it's also not a feature request. It is a problem however. 

The "All checks have passed" part of the pull request disappers when this action is run.

**To Reproduce**
1. Run a workflow that runs some actions (but not this one)
2. When they complete you'll get "All checks have passed, X successful checks"
3. Run a workflow using this action (or a manual commit).
4. The "All checks have passed" disappears, I assume because the pull request has now changed.

**Expected behavior**
The "All checks have passed" part should still display after the commit.

**Comment by stefanzweifel** [comment]
(Sorry for the delay. I enjoyed a vacation in a remote place without internet and was only now able to answer this issue)

I think this "problem" is related to the fact that the commit created by this Action doesn't trigger a new CI build and therefore the status checks are not updated.
And as this Action creates a commit, GitHub hides the "All Checks have passed" message, as it's no longer up to date/relevant.

This is "by design" by GitHub. There is currently no save way to circumvent this.
Another user recently opened a similar issue: #38.

You might take a look a some of the proposed solutions [here](https://github.com/stefanzweifel/git-auto-commit-action/issues/38#issuecomment-580174859). The most practical solution for you might be to create a Personal Access Token and use that instead of the `GITHUB_TOKEN`.

---

There are still some issues open on this repo, which are all kinda related to the `GITHUB_TOKEN` and how the Action authenticates with GitHub. I will go through these issues over the next days, release v3.0.0 and also write some documentation/FAQ related to your "problem".

**Comment by dellow** [comment]
No problem at all. Hope you had a great vacation!

Thanks I will check out the other solutions. Closing this now.
