### ISSUE TITLE
Commits not pushed when tag is defined

### ISSUE THREAD

**Issue by piranna** [stefanzweifel/git-auto-commit-action#69]
https://github.com/stefanzweifel/git-auto-commit-action/blob/2f5e73df85349efb9d2c4143b0bc601e271fff97/entrypoint.sh#L82

At https://github.com/projectlint/OS-lifecycle/runs/628003780?check_suite_focus=true I've found that the tags are being pushed, but it fails because `master` branch didn't, like it was did at https://github.com/projectlint/OS-lifecycle/runs/451499219?check_suite_focus=true. 

I've searching for this and according to https://stackoverflow.com/q/57905137/586382 and https://stackoverflow.com/q/3745135/586382, seems when using the `--tags` flag only the tags are being send, NOT the commits of the actual branch if not set explicitly in the command line, as it's being done at https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L90 when branch name is provided. 

Maybe `INPUT_BRANCH` could be initialized to current branch at https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L39-L44 if it's not provided, and code https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L75-L92 unified and simplified?

**Comment by stefanzweifel** [comment]
(Note: I've edited your comment and added some line breaks to make it easier to read.)

I think this boils down to a misunderstanding and not documented "feature" of the Action. 

The metioned [workflow run](https://github.com/projectlint/OS-lifecycle/runs/628003780?check_suite_focus=true#step:5:27) fails due to the following error:

```
To https://github.com/projectlint/OS-lifecycle
 ! [rejected]        2020.4.26 -> 2020.4.26 (already exists)
error: failed to push some refs to 'https://github.com/projectlint/OS-lifecycle'
hint: Updates were rejected because the tag already exists in the remote.
```

A tag has already been pushed: https://github.com/projectlint/OS-lifecycle/releases/tag/2020.4.26
(I don't know if this happened manually or through the action).

---

Concerning default value for the `INPUT_BRANCH`: This sounds like a good idea, but the Action is highly dependent on the `actions/checkout`-Action and its configuration. In addition, the event through which the workflow is triggered is also important.

In the linked workflow, the tag is created during a schedule. Should the Action then assume that the default branch is `master`? Or should the Action do an evaluation, what the configured default branch on the repo is?

In my opinion, this leads just to more confusion. Hardcoding the `branch`-value in this case would be the simplest solution.

I've purposely built this Action do not rely on "clever" default values. Rewriting the README/docs to reflect that, would hopefully solve similar questions/issues in the future.

**Comment by piranna** [comment]
> (Note: I've edited your comment and added some line breaks to make it easier to read.)

Fine for me :+1: 


> A tag has already been pushed: [projectlint/OS-lifecycle@`2020.4.26` (release)](https://github.com/projectlint/OS-lifecycle/releases/tag/2020.4.26)
> (I don't know if this happened manually or through the action).

My fault. Yes, it was pushed yesterday at https://github.com/projectlint/OS-lifecycle/runs/625828662?check_suite_focus=true, sorry for not explain it.


> In the linked workflow, the tag is created during a schedule. Should the Action then assume that the default branch is `master`? Or should the Action do an evaluation, what the configured default branch on the repo is?

Good question. To my undestand, default branch should be always the one where the code is being fetched, being this a pull-request, a push or a scheduled task.
Least surprise principle, if I fetch from `master` i expect commits being pushed to `master`, if I fetched a pull-request branch, commits must be pushed to that pull-request branch, etc.


> I've purposely built this Action do not rely on "clever" default values. Rewriting the README/docs to reflect that, would hopefully solve similar questions/issues in the future.

Not a bad idea, but this lack of intelligence would make it more difficult cases like the pull-request one because it's not possible to know the branch name in advance, isn't it?

**Comment by piranna** [comment]
> However, in workflows which are scheduled, this probably doesn't work.
> In your case, I would rewrite the workflow to look like this

Yes, for some reason it's not working in the scheduled action, but the `branch: master` thing worked, thank you :-)


> I think highlighting the most common uses cases and pitfalls in the README would be a great idea. I will work on this over the next days.

I tend to make my APIs as simple as possible and making it "just works" by default, but since the functionality is already available and it would be sugar syntax, I find it ok to fix it by adding examples in the readme :-)

**Comment by stefanzweifel** [comment]
> I tend to make my APIs as simple as possible and making it "just works" by default, but since the functionality is already available and it would be sugar syntax, […]

That's the plan when I rewrite the Action in JS or TS somewhen in the future. Making a shell script super developer friendly is honestly quite hard (my lack of shell script knowledge also doesn't help here 😅)

**Comment by joemaller** [comment]
Hi, maybe related. I've got an action triggering on a tag push:

```yaml
  push:
    tags: ["v*"]
```
GitHub actions seems to checkout the code with a detached head, and trying to push using your action fails with this error:
```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.6/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.6/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

Specifying `branch: master` and `branch: origin/master` don't work, `github.head_ref` isn't defined for this event.

**Comment by stefanzweifel** [comment]
@joemaller Seems related.
The problem is, that the `actions/checkout` Action leaves the repo in a detached state. (Honestly, it's the most frustrating problem in relation to this project)

I can't give a solution right now. First have to read the docs again 😅.
Would be great if you could open a new issue for this, as it's related to the "tags push" event.

Also, please share your workflow code or parts of it. And maybe a short description what you want to accomplish with `git-auto-commit` in your project.

**Comment by piranna** [comment]
Tags are mostly like alias for commits, the same for branches. Only solution here is to do a checkout to a branch later (that could be pointing to the same commit than the tag).
